package WatchmanModule;


/**
* WatchmanModule/Watchman.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IDLWatchmanModule.idl
* Segunda-feira, 15 de Outubro de 2018 18h40min24s GMT-03:00
*/

public interface Watchman extends WatchmanOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Watchman
