package WatchmanModule;


/**
* WatchmanModule/WatchmanOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IDLWatchmanModule.idl
* Segunda-feira, 15 de Outubro de 2018 11h36min23s GMT-03:00
*/

public interface WatchmanOperations 
{
  void setTurn (String turn);
  void updateCount (int count);
} // interface WatchmanOperations
