package SystemControl;

/**
* SystemControl/MuseumHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MuseumSystemControlIDL.idl
* Domingo, 14 de Outubro de 2018 17h05min45s GMT-03:00
*/

public final class MuseumHolder implements org.omg.CORBA.portable.Streamable
{
  public SystemControl.Museum value = null;

  public MuseumHolder ()
  {
  }

  public MuseumHolder (SystemControl.Museum initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = SystemControl.MuseumHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    SystemControl.MuseumHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return SystemControl.MuseumHelper.type ();
  }

}
