package SystemControl;


/**
* SystemControl/MuseumOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MuseumSystemControlIDL.idl
* Domingo, 14 de Outubro de 2018 17h05min45s GMT-03:00
*/

public interface MuseumOperations 
{
  int addVisitor ();
  int decreaseVisitor ();
} // interface MuseumOperations
