package SystemControl;


/**
* SystemControl/MuseumHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MuseumSystemControlIDL.idl
* Domingo, 14 de Outubro de 2018 17h05min45s GMT-03:00
*/

abstract public class MuseumHelper
{
  private static String  _id = "IDL:SystemControl/Museum:1.0";

  public static void insert (org.omg.CORBA.Any a, SystemControl.Museum that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static SystemControl.Museum extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (SystemControl.MuseumHelper.id (), "Museum");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static SystemControl.Museum read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_MuseumStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, SystemControl.Museum value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static SystemControl.Museum narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof SystemControl.Museum)
      return (SystemControl.Museum)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      SystemControl._MuseumStub stub = new SystemControl._MuseumStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static SystemControl.Museum unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof SystemControl.Museum)
      return (SystemControl.Museum)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      SystemControl._MuseumStub stub = new SystemControl._MuseumStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
