package BellModule;


/**
* BellModule/Bell.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BellModuleIDL.idl
* Domingo, 14 de Outubro de 2018 18h12min37s GMT-03:00
*/

public interface Bell extends BellOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Bell
