package BellModule;


/**
* BellModule/BellOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IDLBellModule.idl
* Quarta-feira, 17 de Outubro de 2018 00h42min12s GMT-03:00
*/

public interface BellOperations 
{
  void ring ();
  void stop ();
} // interface BellOperations
