package BellModule;


/**
* BellModule/Bell.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IDLBellModule.idl
* Quarta-feira, 17 de Outubro de 2018 00h42min12s GMT-03:00
*/

public interface Bell extends BellOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Bell
