package BellModule;

/**
* BellModule/BellHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IDLBellModule.idl
* Quarta-feira, 17 de Outubro de 2018 00h42min12s GMT-03:00
*/

public final class BellHolder implements org.omg.CORBA.portable.Streamable
{
  public BellModule.Bell value = null;

  public BellHolder ()
  {
  }

  public BellHolder (BellModule.Bell initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BellModule.BellHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BellModule.BellHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BellModule.BellHelper.type ();
  }

}
