package BellModule;


/**
* BellModule/BellOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BellModuleIDL.idl
* Domingo, 14 de Outubro de 2018 18h12min37s GMT-03:00
*/

public interface BellOperations 
{
  void ring ();
} // interface BellOperations
