package Matematica;


/**
* Matematica/Calculadora.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CalcIDL.idl
* Domingo, 14 de Outubro de 2018 11h13min34s GMT-03:00
*/

public interface Calculadora extends CalculadoraOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Calculadora
