package GateModule;


/**
* GateModule/GateHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IDLGateModule.idl
* Segunda-feira, 15 de Outubro de 2018 11h12min10s GMT-03:00
*/

abstract public class GateHelper
{
  private static String  _id = "IDL:GateModule/Gate:1.0";

  public static void insert (org.omg.CORBA.Any a, GateModule.Gate that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static GateModule.Gate extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (GateModule.GateHelper.id (), "Gate");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static GateModule.Gate read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_GateStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, GateModule.Gate value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static GateModule.Gate narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof GateModule.Gate)
      return (GateModule.Gate)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      GateModule._GateStub stub = new GateModule._GateStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static GateModule.Gate unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof GateModule.Gate)
      return (GateModule.Gate)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      GateModule._GateStub stub = new GateModule._GateStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
