package GateModule;


/**
* GateModule/GatePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GateModuleIDL.idl
* Domingo, 14 de Outubro de 2018 17h47min44s GMT-03:00
*/

public abstract class GatePOA extends org.omg.PortableServer.Servant
 implements GateModule.GateOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("addVisitor", new java.lang.Integer (0));
    _methods.put ("decreaseVisitor", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // GateModule/Gate/addVisitor
       {
         int $result = (int)0;
         $result = this.addVisitor ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // GateModule/Gate/decreaseVisitor
       {
         int $result = (int)0;
         $result = this.decreaseVisitor ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:GateModule/Gate:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Gate _this() 
  {
    return GateHelper.narrow(
    super._this_object());
  }

  public Gate _this(org.omg.CORBA.ORB orb) 
  {
    return GateHelper.narrow(
    super._this_object(orb));
  }


} // class GatePOA
