package GateModule;


/**
* GateModule/Gate.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GateModuleIDL.idl
* Domingo, 14 de Outubro de 2018 17h47min44s GMT-03:00
*/

public interface Gate extends GateOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Gate
