package GateModule;


/**
* GateModule/GateOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IDLGateModule.idl
* Segunda-feira, 15 de Outubro de 2018 18h40min26s GMT-03:00
*/

public interface GateOperations 
{
  int addVisitor ();
  int decreaseVisitor ();
  void updateCount (int count);
  int getCount ();
} // interface GateOperations
